/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as DataManagementRouteImport } from './routes/data-management'
import { Route as EnergyRouteImport } from './routes/energy'
import { Route as ImportExportRouteImport } from './routes/import-export'
import { Route as IndustrialClustersRouteImport } from './routes/industrial-clusters'
import { Route as IndustryDatabaseRouteImport } from './routes/industry-database'
import { Route as IntegrationRouteImport } from './routes/integration'
import { Route as MarketRouteImport } from './routes/market'
import { Route as PlatformOverviewRouteImport } from './routes/platform-overview'
import { Route as TradePromotionRouteImport } from './routes/trade-promotion'
import { Route as TrangThongTinRouteImport } from './routes/trang-thong-tin'
import { Route as EnergyCarbonRouteImport } from './routes/energy.carbon'
import { Route as EnergyChargingStationsRouteImport } from './routes/energy.charging-stations'
import { Route as EnergyConsumptionRouteImport } from './routes/energy.consumption'
import { Route as EnergyGisRouteImport } from './routes/energy.gis'
import { Route as EnergyGridRouteImport } from './routes/energy.grid'
import { Route as EnergyGridSafetyRouteImport } from './routes/energy.grid-safety'
import { Route as EnergyNhiemVu1RouteImport } from './routes/energy.nhiem-vu-1'
import { Route as EnergyNhiemVu2RouteImport } from './routes/energy.nhiem-vu-2'
import { Route as EnergyNhiemVu3RouteImport } from './routes/energy.nhiem-vu-3'
import { Route as EnergyNhiemVu4RouteImport } from './routes/energy.nhiem-vu-4'
import { Route as EnergyNhiemVu5RouteImport } from './routes/energy.nhiem-vu-5'
import { Route as EnergyNhiemVu6RouteImport } from './routes/energy.nhiem-vu-6'
import { Route as EnergyNhiemVu7RouteImport } from './routes/energy.nhiem-vu-7'
import { Route as EnergyProjectsRouteImport } from './routes/energy.projects'
import { Route as EnergyRooftopSolarRouteImport } from './routes/energy.rooftop-solar'
import { Route as EnterprisesIdRouteImport } from './routes/enterprises/$id'
import { Route as GisMapRouteImport } from './routes/gis.map'
import { Route as TrangThongTinLanhDaoDonViRouteImport } from './routes/trang-thong-tin/lanh-dao-don-vi'
import { Route as TrangThongTinDauTuSlugRouteImport } from './routes/trang-thong-tin/dau-tu.$slug'
import { Route as TrangThongTinSuKienSlugRouteImport } from './routes/trang-thong-tin/su-kien.$slug'
import { Route as TrangThongTinTinSlugRouteImport } from './routes/trang-thong-tin/tin.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DataManagementRoute = DataManagementRouteImport.update({
  id: '/data-management',
  path: '/data-management',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergyRoute = EnergyRouteImport.update({
  id: '/energy',
  path: '/energy',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportExportRoute = ImportExportRouteImport.update({
  id: '/import-export',
  path: '/import-export',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustrialClustersRoute = IndustrialClustersRouteImport.update({
  id: '/industrial-clusters',
  path: '/industrial-clusters',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryDatabaseRoute = IndustryDatabaseRouteImport.update({
  id: '/industry-database',
  path: '/industry-database',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationRoute = IntegrationRouteImport.update({
  id: '/integration',
  path: '/integration',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformOverviewRoute = PlatformOverviewRouteImport.update({
  id: '/platform-overview',
  path: '/platform-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const TradePromotionRoute = TradePromotionRouteImport.update({
  id: '/trade-promotion',
  path: '/trade-promotion',
  getParentRoute: () => rootRouteImport,
} as any)
const TrangThongTinRoute = TrangThongTinRouteImport.update({
  id: '/trang-thong-tin',
  path: '/trang-thong-tin',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergyCarbonRoute = EnergyCarbonRouteImport.update({
  id: '/carbon',
  path: '/carbon',
  getParentRoute: () => EnergyRoute,
} as any)
const EnergyChargingStationsRoute = EnergyChargingStationsRouteImport.update({
  id: '/charging-stations',
  path: '/charging-stations',
  getParentRoute: () => EnergyRoute,
} as any)
const EnergyConsumptionRoute = EnergyConsumptionRouteImport.update({
  id: '/consumption',
  path: '/consumption',
  getParentRoute: () => EnergyRoute,
} as any)
const EnergyGisRoute = EnergyGisRouteImport.update({
  id: '/gis',
  path: '/gis',
  getParentRoute: () => EnergyRoute,
} as any)
const EnergyGridRoute = EnergyGridRouteImport.update({
  id: '/grid',
  path: '/grid',
  getParentRoute: () => EnergyRoute,
} as any)
const EnergyGridSafetyRoute = EnergyGridSafetyRouteImport.update({
  id: '/grid-safety',
  path: '/grid-safety',
  getParentRoute: () => EnergyRoute,
} as any)
const EnergyNhiemVu1Route = EnergyNhiemVu1RouteImport.update({
  id: '/nhiem-vu-1',
  path: '/nhiem-vu-1',
  getParentRoute: () => EnergyRoute,
} as any)
const EnergyNhiemVu2Route = EnergyNhiemVu2RouteImport.update({
  id: '/nhiem-vu-2',
  path: '/nhiem-vu-2',
  getParentRoute: () => EnergyRoute,
} as any)
const EnergyNhiemVu3Route = EnergyNhiemVu3RouteImport.update({
  id: '/nhiem-vu-3',
  path: '/nhiem-vu-3',
  getParentRoute: () => EnergyRoute,
} as any)
const EnergyNhiemVu4Route = EnergyNhiemVu4RouteImport.update({
  id: '/nhiem-vu-4',
  path: '/nhiem-vu-4',
  getParentRoute: () => EnergyRoute,
} as any)
const EnergyNhiemVu5Route = EnergyNhiemVu5RouteImport.update({
  id: '/nhiem-vu-5',
  path: '/nhiem-vu-5',
  getParentRoute: () => EnergyRoute,
} as any)
const EnergyNhiemVu6Route = EnergyNhiemVu6RouteImport.update({
  id: '/nhiem-vu-6',
  path: '/nhiem-vu-6',
  getParentRoute: () => EnergyRoute,
} as any)
const EnergyNhiemVu7Route = EnergyNhiemVu7RouteImport.update({
  id: '/nhiem-vu-7',
  path: '/nhiem-vu-7',
  getParentRoute: () => EnergyRoute,
} as any)
const EnergyProjectsRoute = EnergyProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => EnergyRoute,
} as any)
const EnergyRooftopSolarRoute = EnergyRooftopSolarRouteImport.update({
  id: '/rooftop-solar',
  path: '/rooftop-solar',
  getParentRoute: () => EnergyRoute,
} as any)
const EnterprisesIdRoute = EnterprisesIdRouteImport.update({
  id: '/enterprises/$id',
  path: '/enterprises/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GisMapRoute = GisMapRouteImport.update({
  id: '/gis/map',
  path: '/gis/map',
  getParentRoute: () => rootRouteImport,
} as any)
const TrangThongTinLanhDaoDonViRoute =
  TrangThongTinLanhDaoDonViRouteImport.update({
    id: '/lanh-dao-don-vi',
    path: '/lanh-dao-don-vi',
    getParentRoute: () => TrangThongTinRoute,
  } as any)
const TrangThongTinDauTuSlugRoute = TrangThongTinDauTuSlugRouteImport.update({
  id: '/dau-tu/$slug',
  path: '/dau-tu/$slug',
  getParentRoute: () => TrangThongTinRoute,
} as any)
const TrangThongTinSuKienSlugRoute = TrangThongTinSuKienSlugRouteImport.update({
  id: '/su-kien/$slug',
  path: '/su-kien/$slug',
  getParentRoute: () => TrangThongTinRoute,
} as any)
const TrangThongTinTinSlugRoute = TrangThongTinTinSlugRouteImport.update({
  id: '/tin/$slug',
  path: '/tin/$slug',
  getParentRoute: () => TrangThongTinRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/data-management': typeof DataManagementRoute
  '/energy': typeof EnergyRouteWithChildren
  '/import-export': typeof ImportExportRoute
  '/industrial-clusters': typeof IndustrialClustersRoute
  '/industry-database': typeof IndustryDatabaseRoute
  '/integration': typeof IntegrationRoute
  '/market': typeof MarketRoute
  '/platform-overview': typeof PlatformOverviewRoute
  '/trade-promotion': typeof TradePromotionRoute
  '/trang-thong-tin': typeof TrangThongTinRouteWithChildren
  '/energy/carbon': typeof EnergyCarbonRoute
  '/energy/charging-stations': typeof EnergyChargingStationsRoute
  '/energy/consumption': typeof EnergyConsumptionRoute
  '/energy/gis': typeof EnergyGisRoute
  '/energy/grid': typeof EnergyGridRoute
  '/energy/grid-safety': typeof EnergyGridSafetyRoute
  '/energy/nhiem-vu-1': typeof EnergyNhiemVu1Route
  '/energy/nhiem-vu-2': typeof EnergyNhiemVu2Route
  '/energy/nhiem-vu-3': typeof EnergyNhiemVu3Route
  '/energy/nhiem-vu-4': typeof EnergyNhiemVu4Route
  '/energy/nhiem-vu-5': typeof EnergyNhiemVu5Route
  '/energy/nhiem-vu-6': typeof EnergyNhiemVu6Route
  '/energy/nhiem-vu-7': typeof EnergyNhiemVu7Route
  '/energy/projects': typeof EnergyProjectsRoute
  '/energy/rooftop-solar': typeof EnergyRooftopSolarRoute
  '/enterprises/$id': typeof EnterprisesIdRoute
  '/gis/map': typeof GisMapRoute
  '/trang-thong-tin/lanh-dao-don-vi': typeof TrangThongTinLanhDaoDonViRoute
  '/trang-thong-tin/dau-tu/$slug': typeof TrangThongTinDauTuSlugRoute
  '/trang-thong-tin/su-kien/$slug': typeof TrangThongTinSuKienSlugRoute
  '/trang-thong-tin/tin/$slug': typeof TrangThongTinTinSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/data-management': typeof DataManagementRoute
  '/energy': typeof EnergyRouteWithChildren
  '/import-export': typeof ImportExportRoute
  '/industrial-clusters': typeof IndustrialClustersRoute
  '/industry-database': typeof IndustryDatabaseRoute
  '/integration': typeof IntegrationRoute
  '/market': typeof MarketRoute
  '/platform-overview': typeof PlatformOverviewRoute
  '/trade-promotion': typeof TradePromotionRoute
  '/trang-thong-tin': typeof TrangThongTinRouteWithChildren
  '/energy/carbon': typeof EnergyCarbonRoute
  '/energy/charging-stations': typeof EnergyChargingStationsRoute
  '/energy/consumption': typeof EnergyConsumptionRoute
  '/energy/gis': typeof EnergyGisRoute
  '/energy/grid': typeof EnergyGridRoute
  '/energy/grid-safety': typeof EnergyGridSafetyRoute
  '/energy/nhiem-vu-1': typeof EnergyNhiemVu1Route
  '/energy/nhiem-vu-2': typeof EnergyNhiemVu2Route
  '/energy/nhiem-vu-3': typeof EnergyNhiemVu3Route
  '/energy/nhiem-vu-4': typeof EnergyNhiemVu4Route
  '/energy/nhiem-vu-5': typeof EnergyNhiemVu5Route
  '/energy/nhiem-vu-6': typeof EnergyNhiemVu6Route
  '/energy/nhiem-vu-7': typeof EnergyNhiemVu7Route
  '/energy/projects': typeof EnergyProjectsRoute
  '/energy/rooftop-solar': typeof EnergyRooftopSolarRoute
  '/enterprises/$id': typeof EnterprisesIdRoute
  '/gis/map': typeof GisMapRoute
  '/trang-thong-tin/lanh-dao-don-vi': typeof TrangThongTinLanhDaoDonViRoute
  '/trang-thong-tin/dau-tu/$slug': typeof TrangThongTinDauTuSlugRoute
  '/trang-thong-tin/su-kien/$slug': typeof TrangThongTinSuKienSlugRoute
  '/trang-thong-tin/tin/$slug': typeof TrangThongTinTinSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/data-management': typeof DataManagementRoute
  '/energy': typeof EnergyRouteWithChildren
  '/import-export': typeof ImportExportRoute
  '/industrial-clusters': typeof IndustrialClustersRoute
  '/industry-database': typeof IndustryDatabaseRoute
  '/integration': typeof IntegrationRoute
  '/market': typeof MarketRoute
  '/platform-overview': typeof PlatformOverviewRoute
  '/trade-promotion': typeof TradePromotionRoute
  '/trang-thong-tin': typeof TrangThongTinRouteWithChildren
  '/energy/carbon': typeof EnergyCarbonRoute
  '/energy/charging-stations': typeof EnergyChargingStationsRoute
  '/energy/consumption': typeof EnergyConsumptionRoute
  '/energy/gis': typeof EnergyGisRoute
  '/energy/grid': typeof EnergyGridRoute
  '/energy/grid-safety': typeof EnergyGridSafetyRoute
  '/energy/nhiem-vu-1': typeof EnergyNhiemVu1Route
  '/energy/nhiem-vu-2': typeof EnergyNhiemVu2Route
  '/energy/nhiem-vu-3': typeof EnergyNhiemVu3Route
  '/energy/nhiem-vu-4': typeof EnergyNhiemVu4Route
  '/energy/nhiem-vu-5': typeof EnergyNhiemVu5Route
  '/energy/nhiem-vu-6': typeof EnergyNhiemVu6Route
  '/energy/nhiem-vu-7': typeof EnergyNhiemVu7Route
  '/energy/projects': typeof EnergyProjectsRoute
  '/energy/rooftop-solar': typeof EnergyRooftopSolarRoute
  '/enterprises/$id': typeof EnterprisesIdRoute
  '/gis/map': typeof GisMapRoute
  '/trang-thong-tin/lanh-dao-don-vi': typeof TrangThongTinLanhDaoDonViRoute
  '/trang-thong-tin/dau-tu/$slug': typeof TrangThongTinDauTuSlugRoute
  '/trang-thong-tin/su-kien/$slug': typeof TrangThongTinSuKienSlugRoute
  '/trang-thong-tin/tin/$slug': typeof TrangThongTinTinSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/data-management'
    | '/energy'
    | '/import-export'
    | '/industrial-clusters'
    | '/industry-database'
    | '/integration'
    | '/market'
    | '/platform-overview'
    | '/trade-promotion'
    | '/trang-thong-tin'
    | '/energy/carbon'
    | '/energy/charging-stations'
    | '/energy/consumption'
    | '/energy/gis'
    | '/energy/grid'
    | '/energy/grid-safety'
    | '/energy/nhiem-vu-1'
    | '/energy/nhiem-vu-2'
    | '/energy/nhiem-vu-3'
    | '/energy/nhiem-vu-4'
    | '/energy/nhiem-vu-5'
    | '/energy/nhiem-vu-6'
    | '/energy/nhiem-vu-7'
    | '/energy/projects'
    | '/energy/rooftop-solar'
    | '/enterprises/$id'
    | '/gis/map'
    | '/trang-thong-tin/lanh-dao-don-vi'
    | '/trang-thong-tin/dau-tu/$slug'
    | '/trang-thong-tin/su-kien/$slug'
    | '/trang-thong-tin/tin/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/data-management'
    | '/energy'
    | '/import-export'
    | '/industrial-clusters'
    | '/industry-database'
    | '/integration'
    | '/market'
    | '/platform-overview'
    | '/trade-promotion'
    | '/trang-thong-tin'
    | '/energy/carbon'
    | '/energy/charging-stations'
    | '/energy/consumption'
    | '/energy/gis'
    | '/energy/grid'
    | '/energy/grid-safety'
    | '/energy/nhiem-vu-1'
    | '/energy/nhiem-vu-2'
    | '/energy/nhiem-vu-3'
    | '/energy/nhiem-vu-4'
    | '/energy/nhiem-vu-5'
    | '/energy/nhiem-vu-6'
    | '/energy/nhiem-vu-7'
    | '/energy/projects'
    | '/energy/rooftop-solar'
    | '/enterprises/$id'
    | '/gis/map'
    | '/trang-thong-tin/lanh-dao-don-vi'
    | '/trang-thong-tin/dau-tu/$slug'
    | '/trang-thong-tin/su-kien/$slug'
    | '/trang-thong-tin/tin/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/data-management'
    | '/energy'
    | '/import-export'
    | '/industrial-clusters'
    | '/industry-database'
    | '/integration'
    | '/market'
    | '/platform-overview'
    | '/trade-promotion'
    | '/trang-thong-tin'
    | '/energy/carbon'
    | '/energy/charging-stations'
    | '/energy/consumption'
    | '/energy/gis'
    | '/energy/grid'
    | '/energy/grid-safety'
    | '/energy/nhiem-vu-1'
    | '/energy/nhiem-vu-2'
    | '/energy/nhiem-vu-3'
    | '/energy/nhiem-vu-4'
    | '/energy/nhiem-vu-5'
    | '/energy/nhiem-vu-6'
    | '/energy/nhiem-vu-7'
    | '/energy/projects'
    | '/energy/rooftop-solar'
    | '/enterprises/$id'
    | '/gis/map'
    | '/trang-thong-tin/lanh-dao-don-vi'
    | '/trang-thong-tin/dau-tu/$slug'
    | '/trang-thong-tin/su-kien/$slug'
    | '/trang-thong-tin/tin/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DataManagementRoute: typeof DataManagementRoute
  EnergyRoute: typeof EnergyRouteWithChildren
  ImportExportRoute: typeof ImportExportRoute
  IndustrialClustersRoute: typeof IndustrialClustersRoute
  IndustryDatabaseRoute: typeof IndustryDatabaseRoute
  IntegrationRoute: typeof IntegrationRoute
  MarketRoute: typeof MarketRoute
  PlatformOverviewRoute: typeof PlatformOverviewRoute
  TradePromotionRoute: typeof TradePromotionRoute
  TrangThongTinRoute: typeof TrangThongTinRouteWithChildren
  EnterprisesIdRoute: typeof EnterprisesIdRoute
  GisMapRoute: typeof GisMapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-management': {
      id: '/data-management'
      path: '/data-management'
      fullPath: '/data-management'
      preLoaderRoute: typeof DataManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energy': {
      id: '/energy'
      path: '/energy'
      fullPath: '/energy'
      preLoaderRoute: typeof EnergyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-export': {
      id: '/import-export'
      path: '/import-export'
      fullPath: '/import-export'
      preLoaderRoute: typeof ImportExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industrial-clusters': {
      id: '/industrial-clusters'
      path: '/industrial-clusters'
      fullPath: '/industrial-clusters'
      preLoaderRoute: typeof IndustrialClustersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-database': {
      id: '/industry-database'
      path: '/industry-database'
      fullPath: '/industry-database'
      preLoaderRoute: typeof IndustryDatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration': {
      id: '/integration'
      path: '/integration'
      fullPath: '/integration'
      preLoaderRoute: typeof IntegrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform-overview': {
      id: '/platform-overview'
      path: '/platform-overview'
      fullPath: '/platform-overview'
      preLoaderRoute: typeof PlatformOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade-promotion': {
      id: '/trade-promotion'
      path: '/trade-promotion'
      fullPath: '/trade-promotion'
      preLoaderRoute: typeof TradePromotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trang-thong-tin': {
      id: '/trang-thong-tin'
      path: '/trang-thong-tin'
      fullPath: '/trang-thong-tin'
      preLoaderRoute: typeof TrangThongTinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energy/carbon': {
      id: '/energy/carbon'
      path: '/carbon'
      fullPath: '/energy/carbon'
      preLoaderRoute: typeof EnergyCarbonRouteImport
      parentRoute: typeof EnergyRoute
    }
    '/energy/charging-stations': {
      id: '/energy/charging-stations'
      path: '/charging-stations'
      fullPath: '/energy/charging-stations'
      preLoaderRoute: typeof EnergyChargingStationsRouteImport
      parentRoute: typeof EnergyRoute
    }
    '/energy/consumption': {
      id: '/energy/consumption'
      path: '/consumption'
      fullPath: '/energy/consumption'
      preLoaderRoute: typeof EnergyConsumptionRouteImport
      parentRoute: typeof EnergyRoute
    }
    '/energy/gis': {
      id: '/energy/gis'
      path: '/gis'
      fullPath: '/energy/gis'
      preLoaderRoute: typeof EnergyGisRouteImport
      parentRoute: typeof EnergyRoute
    }
    '/energy/grid': {
      id: '/energy/grid'
      path: '/grid'
      fullPath: '/energy/grid'
      preLoaderRoute: typeof EnergyGridRouteImport
      parentRoute: typeof EnergyRoute
    }
    '/energy/grid-safety': {
      id: '/energy/grid-safety'
      path: '/grid-safety'
      fullPath: '/energy/grid-safety'
      preLoaderRoute: typeof EnergyGridSafetyRouteImport
      parentRoute: typeof EnergyRoute
    }
    '/energy/nhiem-vu-1': {
      id: '/energy/nhiem-vu-1'
      path: '/nhiem-vu-1'
      fullPath: '/energy/nhiem-vu-1'
      preLoaderRoute: typeof EnergyNhiemVu1RouteImport
      parentRoute: typeof EnergyRoute
    }
    '/energy/nhiem-vu-2': {
      id: '/energy/nhiem-vu-2'
      path: '/nhiem-vu-2'
      fullPath: '/energy/nhiem-vu-2'
      preLoaderRoute: typeof EnergyNhiemVu2RouteImport
      parentRoute: typeof EnergyRoute
    }
    '/energy/nhiem-vu-3': {
      id: '/energy/nhiem-vu-3'
      path: '/nhiem-vu-3'
      fullPath: '/energy/nhiem-vu-3'
      preLoaderRoute: typeof EnergyNhiemVu3RouteImport
      parentRoute: typeof EnergyRoute
    }
    '/energy/nhiem-vu-4': {
      id: '/energy/nhiem-vu-4'
      path: '/nhiem-vu-4'
      fullPath: '/energy/nhiem-vu-4'
      preLoaderRoute: typeof EnergyNhiemVu4RouteImport
      parentRoute: typeof EnergyRoute
    }
    '/energy/nhiem-vu-5': {
      id: '/energy/nhiem-vu-5'
      path: '/nhiem-vu-5'
      fullPath: '/energy/nhiem-vu-5'
      preLoaderRoute: typeof EnergyNhiemVu5RouteImport
      parentRoute: typeof EnergyRoute
    }
    '/energy/nhiem-vu-6': {
      id: '/energy/nhiem-vu-6'
      path: '/nhiem-vu-6'
      fullPath: '/energy/nhiem-vu-6'
      preLoaderRoute: typeof EnergyNhiemVu6RouteImport
      parentRoute: typeof EnergyRoute
    }
    '/energy/nhiem-vu-7': {
      id: '/energy/nhiem-vu-7'
      path: '/nhiem-vu-7'
      fullPath: '/energy/nhiem-vu-7'
      preLoaderRoute: typeof EnergyNhiemVu7RouteImport
      parentRoute: typeof EnergyRoute
    }
    '/energy/projects': {
      id: '/energy/projects'
      path: '/projects'
      fullPath: '/energy/projects'
      preLoaderRoute: typeof EnergyProjectsRouteImport
      parentRoute: typeof EnergyRoute
    }
    '/energy/rooftop-solar': {
      id: '/energy/rooftop-solar'
      path: '/rooftop-solar'
      fullPath: '/energy/rooftop-solar'
      preLoaderRoute: typeof EnergyRooftopSolarRouteImport
      parentRoute: typeof EnergyRoute
    }
    '/enterprises/$id': {
      id: '/enterprises/$id'
      path: '/enterprises/$id'
      fullPath: '/enterprises/$id'
      preLoaderRoute: typeof EnterprisesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gis/map': {
      id: '/gis/map'
      path: '/gis/map'
      fullPath: '/gis/map'
      preLoaderRoute: typeof GisMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trang-thong-tin/lanh-dao-don-vi': {
      id: '/trang-thong-tin/lanh-dao-don-vi'
      path: '/lanh-dao-don-vi'
      fullPath: '/trang-thong-tin/lanh-dao-don-vi'
      preLoaderRoute: typeof TrangThongTinLanhDaoDonViRouteImport
      parentRoute: typeof TrangThongTinRoute
    }
    '/trang-thong-tin/dau-tu/$slug': {
      id: '/trang-thong-tin/dau-tu/$slug'
      path: '/dau-tu/$slug'
      fullPath: '/trang-thong-tin/dau-tu/$slug'
      preLoaderRoute: typeof TrangThongTinDauTuSlugRouteImport
      parentRoute: typeof TrangThongTinRoute
    }
    '/trang-thong-tin/su-kien/$slug': {
      id: '/trang-thong-tin/su-kien/$slug'
      path: '/su-kien/$slug'
      fullPath: '/trang-thong-tin/su-kien/$slug'
      preLoaderRoute: typeof TrangThongTinSuKienSlugRouteImport
      parentRoute: typeof TrangThongTinRoute
    }
    '/trang-thong-tin/tin/$slug': {
      id: '/trang-thong-tin/tin/$slug'
      path: '/tin/$slug'
      fullPath: '/trang-thong-tin/tin/$slug'
      preLoaderRoute: typeof TrangThongTinTinSlugRouteImport
      parentRoute: typeof TrangThongTinRoute
    }
  }
}

interface EnergyRouteChildren {
  EnergyCarbonRoute: typeof EnergyCarbonRoute
  EnergyChargingStationsRoute: typeof EnergyChargingStationsRoute
  EnergyConsumptionRoute: typeof EnergyConsumptionRoute
  EnergyGisRoute: typeof EnergyGisRoute
  EnergyGridRoute: typeof EnergyGridRoute
  EnergyGridSafetyRoute: typeof EnergyGridSafetyRoute
  EnergyNhiemVu1Route: typeof EnergyNhiemVu1Route
  EnergyNhiemVu2Route: typeof EnergyNhiemVu2Route
  EnergyNhiemVu3Route: typeof EnergyNhiemVu3Route
  EnergyNhiemVu4Route: typeof EnergyNhiemVu4Route
  EnergyNhiemVu5Route: typeof EnergyNhiemVu5Route
  EnergyNhiemVu6Route: typeof EnergyNhiemVu6Route
  EnergyNhiemVu7Route: typeof EnergyNhiemVu7Route
  EnergyProjectsRoute: typeof EnergyProjectsRoute
  EnergyRooftopSolarRoute: typeof EnergyRooftopSolarRoute
}

const EnergyRouteChildren: EnergyRouteChildren = {
  EnergyCarbonRoute: EnergyCarbonRoute,
  EnergyChargingStationsRoute: EnergyChargingStationsRoute,
  EnergyConsumptionRoute: EnergyConsumptionRoute,
  EnergyGisRoute: EnergyGisRoute,
  EnergyGridRoute: EnergyGridRoute,
  EnergyGridSafetyRoute: EnergyGridSafetyRoute,
  EnergyNhiemVu1Route: EnergyNhiemVu1Route,
  EnergyNhiemVu2Route: EnergyNhiemVu2Route,
  EnergyNhiemVu3Route: EnergyNhiemVu3Route,
  EnergyNhiemVu4Route: EnergyNhiemVu4Route,
  EnergyNhiemVu5Route: EnergyNhiemVu5Route,
  EnergyNhiemVu6Route: EnergyNhiemVu6Route,
  EnergyNhiemVu7Route: EnergyNhiemVu7Route,
  EnergyProjectsRoute: EnergyProjectsRoute,
  EnergyRooftopSolarRoute: EnergyRooftopSolarRoute,
}

const EnergyRouteWithChildren =
  EnergyRoute._addFileChildren(EnergyRouteChildren)

interface TrangThongTinRouteChildren {
  TrangThongTinLanhDaoDonViRoute: typeof TrangThongTinLanhDaoDonViRoute
  TrangThongTinDauTuSlugRoute: typeof TrangThongTinDauTuSlugRoute
  TrangThongTinSuKienSlugRoute: typeof TrangThongTinSuKienSlugRoute
  TrangThongTinTinSlugRoute: typeof TrangThongTinTinSlugRoute
}

const TrangThongTinRouteChildren: TrangThongTinRouteChildren = {
  TrangThongTinLanhDaoDonViRoute: TrangThongTinLanhDaoDonViRoute,
  TrangThongTinDauTuSlugRoute: TrangThongTinDauTuSlugRoute,
  TrangThongTinSuKienSlugRoute: TrangThongTinSuKienSlugRoute,
  TrangThongTinTinSlugRoute: TrangThongTinTinSlugRoute,
}

const TrangThongTinRouteWithChildren = TrangThongTinRoute._addFileChildren(
  TrangThongTinRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  DataManagementRoute: DataManagementRoute,
  EnergyRoute: EnergyRouteWithChildren,
  ImportExportRoute: ImportExportRoute,
  IndustrialClustersRoute: IndustrialClustersRoute,
  IndustryDatabaseRoute: IndustryDatabaseRoute,
  IntegrationRoute: IntegrationRoute,
  MarketRoute: MarketRoute,
  PlatformOverviewRoute: PlatformOverviewRoute,
  TradePromotionRoute: TradePromotionRoute,
  TrangThongTinRoute: TrangThongTinRouteWithChildren,
  EnterprisesIdRoute: EnterprisesIdRoute,
  GisMapRoute: GisMapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
